#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo echo -e "usage: render <file>.Rmd\n"
    exit
fi

if [ ! -f "$1" ]; then
    echo "$1 does not exist."
    exit
fi

if [[ $1 != *.Rmd ]]; then
    echo "$1 is not an R markdown (Rmd) file."
    exit
fi

## Remove existing output file
F=${1%.*}
F="_posts/${F##*/}.md"
if [[ -f "$F" ]]; then
    rm "$F"
fi

## Render Rmd to md
R -e "library(rmarkdown); render('$1', 'md_document', output_dir='_posts')"
